// Command sitemap-lastmod regenerates internal/view/sitemap_lastmod_gen.go:
// one honest <lastmod> date per sitemap URL, taken from the most recent git
// commit touching that URL's content sources. Files with uncommitted changes
// get today's date (they changed today). Never invents dates.
//
// Usage: go generate ./internal/modules/marketing/
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/David2024patton/patriot-pest-go/internal/data"
)

var pestSlugs = []string{
	"ants", "spiders", "rodents", "bed-bugs", "termites", "mosquitoes",
	"wasps", "cockroaches", "fleas-ticks", "silverfish", "pantry-pests",
	"bees", "squirrels", "raccoons", "bats", "scorpions", "crickets",
	"pack-rats", "box-elder-bugs", "stink-bugs", "fruit-flies", "gophers",
	"moles", "hornets", "yellow-jackets",
}

var postSlugs = []string{
	"why-ants-invade-in-spring", "spiders-fall-guide", "rodent-proof-your-home",
}

var shared = []string{
	"internal/modules/marketing/marketing.go",
	"internal/view/view.go",
}

func main() {
	root := gitRoot()
	sources := map[string][]string{}
	with := func(path string, files ...string) {
		sources[path] = append(shared, files...)
	}
	// Static pages: handler + template file.
	with("/", "internal/view/pages_home.go")
	with("/about", "internal/view/pages_services.go")
	with("/services", "internal/view/pages_services.go")
	with("/prices", "internal/view/pages_prices.go")
	with("/service-areas", "internal/view/pages_areas.go")
	with("/faqs", "internal/view/pages_faqs.go")
	with("/contact", "internal/view/pages_contact.go")
	with("/signup", "internal/modules/marketing/signup.go")
	with("/blogs", "internal/view/pages_blog_index.go")
	with("/referral", "internal/view/pages_referral.go")
	with("/socials", "internal/view/pages_socials.go")
	with("/help", "internal/view/pages_help.go")
	with("/links", "internal/view/pages_links.go")
	with("/privacy-policy", "internal/view/pages_legal.go")
	with("/terms-of-use", "internal/view/pages_legal.go")
	// Pest pages: threat-file template + copy overrides + link tables.
	pestFiles := []string{
		"internal/view/pages_pest.go",
		"internal/view/pest_copy_insects.go",
		"internal/view/pest_copy_wildlife.go",
		"internal/view/pest_overrides.go",
		"internal/view/seo_links.go",
	}
	for _, slug := range pestSlugs {
		sources["/pest/"+slug] = append(append([]string{}, shared...), pestFiles...)
	}
	// City pages: area template + local briefings + link tables.
	areaFiles := []string{
		"internal/view/pages_areas.go",
		"internal/view/area_content.go",
		"internal/view/seo_links.go",
	}
	for _, st := range data.States() {
		for _, city := range st.Cities {
			sources["/areas/"+data.CitySlug(city)] = append(append([]string{}, shared...), areaFiles...)
		}
	}
	// Blog posts: post template + long-form overrides.
	postFiles := []string{
		"internal/view/pages_blog_post.go",
		"internal/view/post_overrides.go",
		"internal/view/seo_links.go",
	}
	for _, slug := range postSlugs {
		sources["/blogs/"+slug] = append(append([]string{}, shared...), postFiles...)
	}

	dirty := dirtyFiles(root)
	today := time.Now().Format("2006-01-02")
	dates := map[string]string{}
	for path, files := range sources {
		for _, f := range files {
			if dirty[f] {
				dates[path] = today
				break
			}
		}
		if _, ok := dates[path]; !ok {
			dates[path] = lastCommitDate(root, files)
		}
	}

	paths := make([]string, 0, len(dates))
	for p := range dates {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	var sb strings.Builder
	sb.WriteString("package view\n\n")
	sb.WriteString("// Code generated by tools/sitemap-lastmod. DO NOT EDIT.\n")
	sb.WriteString("// Regenerate with: go generate ./internal/modules/marketing/\n")
	sb.WriteString("// Each date is the most recent git commit touching that URL's\n")
	sb.WriteString("// content sources (or today, for files with uncommitted changes).\n")
	sb.WriteString("var SitemapLastmod = map[string]string{\n")
	for _, p := range paths {
		fmt.Fprintf(&sb, "\t%q: %q,\n", p, dates[p])
	}
	sb.WriteString("}\n")

	out := filepath.Join(root, "internal/view/sitemap_lastmod_gen.go")
	if err := os.WriteFile(out, []byte(sb.String()), 0644); err != nil {
		fatal(err)
	}
	fmt.Printf("wrote %s (%d urls)\n", out, len(paths))
}

// gitRoot returns the repo top level.
func gitRoot() string {
	out, err := exec.Command("git", "rev-parse", "--show-toplevel").Output()
	if err != nil {
		fatal(err)
	}
	return strings.TrimSpace(string(out))
}

// dirtyFiles returns the set of repo-relative paths with uncommitted changes.
func dirtyFiles(root string) map[string]bool {
	out, err := exec.Command("git", "-C", root, "status", "--porcelain").Output()
	if err != nil {
		fatal(err)
	}
	set := map[string]bool{}
	for _, line := range strings.Split(string(out), "\n") {
		if len(line) < 4 {
			continue
		}
		p := strings.TrimSpace(line[3:])
		// Handle renames ("old -> new"): take the new path.
		if i := strings.Index(p, " -> "); i >= 0 {
			p = p[i+4:]
		}
		// Strip quotes git adds around special paths.
		p = strings.Trim(p, "\"")
		set[p] = true
	}
	return set
}

// lastCommitDate returns the most recent commit date (YYYY-MM-DD) touching
// any of the given repo-relative files, or "" if none have history.
func lastCommitDate(root string, files []string) string {
	args := append([]string{"-C", root, "log", "-1", "--format=%cs", "--"}, files...)
	out, err := exec.Command("git", args...).Output()
	if err != nil {
		fatal(err)
	}
	return strings.TrimSpace(string(out))
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "sitemap-lastmod:", err)
	os.Exit(1)
}
